"""Data tab backend: GET /api/data/inventory, POST /api/data/{browse_files,import,open}.

Shows what's in the user's data folder -- inputs the app reads, files it
generates, and which file each dashboard actually uses -- and lets the user ADD
files by picking them with the native OS dialog; the server then COPIES them into
the right ``storage/`` subfolder. (Server-side copy is the right approach here: a
browser upload would choke on the ~0.5 GB master DBs / 183 MB MeSH files.)
"""

from __future__ import annotations

import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path

from fastapi import APIRouter, HTTPException

from core import paths

router = APIRouter()
_log = logging.getLogger("alexis.api.data")


def _hsize(n: float) -> str:
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if n < 1024 or unit == "TB":
            return f"{int(n)} {unit}" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} TB"


def _categories() -> list[dict]:
    """Declarative map of data categories -> folder, file glob, and role.

    roles: input (you supply it), generated (the app writes it), dashboard
    (a dashboard reads it), output (a final artifact), required.
    mark_latest: flag the newest file as the one the dashboards currently use.
    readonly: cannot be imported into (app-generated artifacts).
    """
    sd = paths.snapshots_dir()
    st = paths.storage_dir()
    return [
        {"key": "mesh", "label": "MeSH reference", "dir": paths.mesh_dir(), "glob": "*",
         "roles": ["input", "required"],
         "desc": "Medical-term reference data. REQUIRED for all classification. Copy your whole mesh folder's files here."},
        {"key": "master", "label": "Master databases", "dir": sd / "active_universe", "glob": "master_DB_*.json",
         "roles": ["input", "dashboard"], "mark_latest": True,
         "desc": "Quarterly full-universe DBs (master_DB_*.json) for trend baselines + 'new' counts. Drop your existing ones here -- no rebuild needed."},
        {"key": "weekly", "label": "US weekly snapshots", "dir": sd / "last_update", "glob": "*.json",
         "roles": ["generated", "dashboard"], "mark_latest": True,
         "desc": "Weekly ClinicalTrials.gov pulls. Generated by the Pull jobs; read by the weekly dashboard."},
        {"key": "changelogs", "label": "US changelogs / enriched", "dir": paths.changelogs_dir(), "glob": "*.json",
         "roles": ["generated", "dashboard"], "mark_latest": True,
         "desc": "Weekly diffs (what's new). Generated by 'Compute weekly changes'; read by the weekly dashboard."},
        {"key": "reclassified", "label": "Reclassified snapshots", "dir": sd / "reclassified", "glob": "*.json",
         "roles": ["generated"],
         "desc": "Snapshots re-run through classification by 'Reclassify a snapshot'."},
        {"key": "chictr", "label": "ChiCTR snapshots (China)", "dir": sd / "chictr", "glob": "*.json",
         "roles": ["generated", "dashboard"], "mark_latest": True,
         "desc": "China snapshots. Generated by 'Classify ChiCTR'; read by the China dashboard tab."},
        {"key": "chictr_changelogs", "label": "ChiCTR changelogs", "dir": st / "chictr_changelogs", "glob": "*.json",
         "roles": ["generated", "dashboard"],
         "desc": "China diffs. Generated by 'Diff two ChiCTR snapshots'."},
        {"key": "anzctr", "label": "ANZCTR snapshots (Australia)", "dir": sd / "anzctr", "glob": "*.json",
         "roles": ["generated", "dashboard"], "mark_latest": True,
         "desc": "Australia snapshots. Generated by 'Classify ANZCTR'; read by the Australia dashboard tab."},
        {"key": "anzctr_changelogs", "label": "ANZCTR changelogs", "dir": st / "anzctr_changelogs", "glob": "*.json",
         "roles": ["generated", "dashboard"],
         "desc": "Australia diffs. Generated by 'Diff two ANZCTR snapshots'."},
        {"key": "dashboards", "label": "Generated dashboards", "dir": paths.viz_dir(), "glob": "*_live.html",
         "roles": ["output"], "readonly": True,
         "desc": "The HTML dashboards the app builds. Open them in the Dashboards tab."},
    ]


def _by_key(key: str) -> dict | None:
    return next((c for c in _categories() if c["key"] == key), None)


def _list_files(d: Path, glob: str) -> list[Path]:
    if not d.is_dir():
        return []
    out = []
    for p in d.glob(glob):
        if p.is_file() and p.suffix != ".pyc" and not p.name.startswith("."):
            out.append(p)
    return out


@router.get("/api/data/inventory")
def inventory() -> dict:
    """Per-category file listing with sizes, roles, and the dashboard-current file."""
    cats = []
    for c in _categories():
        d = c["dir"]
        files = _list_files(d, c["glob"])
        files.sort(key=lambda p: p.stat().st_mtime if p.exists() else 0, reverse=True)
        latest_name = files[0].name if (c.get("mark_latest") and files) else None

        total = 0
        rows = []
        LIMIT = 200
        for i, p in enumerate(files):
            try:
                stt = p.stat()
            except OSError:
                continue
            total += stt.st_size
            if i < LIMIT:
                rows.append({
                    "name": p.name, "size": stt.st_size, "size_h": _hsize(stt.st_size),
                    "mtime": int(stt.st_mtime), "latest": (p.name == latest_name),
                })
        cats.append({
            "key": c["key"], "label": c["label"], "desc": c["desc"],
            "roles": c.get("roles", []), "readonly": bool(c.get("readonly")),
            "dir": str(d), "exists": d.is_dir(),
            "count": len(files), "total_size": total, "total_size_h": _hsize(total),
            "shown": len(rows), "files": rows,
        })
    return {"data_dir": str(paths.data_root()), "categories": cats}


@router.post("/api/data/browse_files")
def browse_files() -> dict:
    """Native multi-file picker via the desktop window. Headless -> unavailable
    (the UI then falls back to typing a path)."""
    try:
        from app.main import get_window
        import webview  # type: ignore
    except Exception:  # noqa: BLE001
        return {"paths": [], "available": False}
    win = get_window()
    if win is None:
        return {"paths": [], "available": False}
    try:
        result = win.create_file_dialog(webview.OPEN_DIALOG, allow_multiple=True)
    except Exception as exc:  # noqa: BLE001
        _log.exception("[err] file dialog failed: %s", exc)
        return {"paths": [], "available": True, "error": str(exc)}
    if not result:
        return {"paths": [], "available": True}   # cancelled
    chosen = list(result) if isinstance(result, (list, tuple)) else [str(result)]
    return {"paths": [str(p) for p in chosen], "available": True}


@router.post("/api/data/import")
def import_files(payload: dict) -> dict:
    """Copy chosen source files into the category's storage folder (server-side).

    Sync def on purpose: FastAPI runs it in a threadpool, so a multi-GB copy
    won't block the event loop / health probe.
    """
    if not isinstance(payload, dict):
        raise HTTPException(status_code=400, detail="payload must be a JSON object")
    key = str(payload.get("category") or "").strip()
    sources = payload.get("sources") or []
    if not isinstance(sources, list) or not sources:
        raise HTTPException(status_code=400, detail="sources (a list of file paths) is required")
    cat = _by_key(key)
    if cat is None:
        raise HTTPException(status_code=400, detail=f"unknown category: {key}")
    if cat.get("readonly"):
        raise HTTPException(status_code=400, detail=f"{cat['label']} is read-only (generated by the app)")

    dest = cat["dir"]
    paths.ensure_dir(dest)
    copied, errors = [], []
    for raw in sources:
        try:
            src = Path(str(raw)).expanduser()
            if not src.is_file():
                errors.append({"path": str(raw), "error": "not a file"})
                continue
            target = dest / src.name
            if src.resolve() == target.resolve():
                copied.append({"name": src.name, "note": "already in place"})
                continue
            shutil.copy2(str(src), str(target))
            copied.append({"name": src.name, "size_h": _hsize(target.stat().st_size)})
        except Exception as exc:  # noqa: BLE001
            _log.exception("[err] import copy failed for %s: %s", raw, exc)
            errors.append({"path": str(raw), "error": type(exc).__name__})
    return {"ok": not errors, "category": key, "dest": str(dest), "copied": copied, "errors": errors}


@router.post("/api/data/open")
def open_folder(payload: dict | None = None) -> dict:
    """Open the data folder (or a category subfolder) in the OS file manager."""
    target = paths.data_root()
    if isinstance(payload, dict) and payload.get("category"):
        cat = _by_key(str(payload["category"]))
        if cat is not None:
            target = cat["dir"]
    paths.ensure_dir(target)
    try:
        if sys.platform == "win32":
            os.startfile(str(target))  # type: ignore[attr-defined]  # noqa: S606
        elif sys.platform == "darwin":
            subprocess.Popen(["open", str(target)])
        else:
            subprocess.Popen(["xdg-open", str(target)])
        return {"ok": True, "path": str(target)}
    except Exception as exc:  # noqa: BLE001
        _log.exception("[err] open folder failed: %s", exc)
        raise HTTPException(status_code=500, detail=f"could not open folder: {type(exc).__name__}")
