import json,os
r=lambda nct,rel,rsn,tgts=None,novel=None:{"nct_id":nct,"relevant":rel,"reasoning":rsn,"targets":tgts or [],"novel_targets":novel or []}
T=lambda t,role,ev:{"target":t,"role":role,"result_use":"bioanalytical","safety_lab":False,"evidence":ev}
N=lambda n,role,ev:{"name":n,"role":role,"result_use":"bioanalytical","evidence":ev}
res=[]
res.append(r('NCT03278925',True,'Phase 1 pilot study validating gamma-OHPdG as a biomarker in cirrhosis patients treated with Polyphenon E; change in gamma-OHPdG expression in liver biopsy is a primary endpoint representing bioanalytical biomarker measurement.',[],[N('gamma-OHPdG','measurement','Change in gamma-hydroxy-1,N(2)-propanodeoxyguanosine (gamma-OHPdG) expression by immunohistochemistry in cirrhotic liver is a primary bioanalytical endpoint')]))
res.append(r('NCT03279094',False,'Phase 1 study of pre-transplant immunosuppressive therapy for haploidentical transplants in sickle cell disease; primary endpoint is unacceptable adverse events rate with engraftment as secondary endpoint; no bioanalytical biomarker measurements described.'))
res.append(r('NCT03279692',True,'Phase 2 study of pembrolizumab (anti-PD-1) in recurrent or residual high-grade meningioma; PD-1 is the molecular target of pembrolizumab and represents a bioanalytical target in the context of drug development.',[T('PD-1','measurement','Pembrolizumab binds PD-1 on activated T cells; PD-1 pathway is the therapeutic target of the investigational agent')]))
res.append(r('NCT03280511',True,'Phase 2 study of PIPAC in resected high-risk colon cancer; free intraperitoneal tumor cells (FITC) detected by peritoneal lavage cytology are measured as secondary bioanalytical biomarkers.',[],[N('FITC','measurement','Free intraperitoneal tumor cells detected by peritoneal lavage cytology are a secondary outcome for bioanalytical assessment of treatment effect')]))
res.append(r('NCT03281954',True,'Phase 3 trial of atezolizumab (anti-PD-L1) plus neoadjuvant chemotherapy in triple-negative breast cancer; PD-L1 is the therapeutic target and tumor samples are required for biomarker research as per eligibility criteria.',[T('PD-L1','measurement','Atezolizumab is an anti-PD-L1 antibody; PD-L1 is the therapeutic target of the investigational agent')]))
res.append(r('NCT03282344',True,'Phase 2 pilot study of NKTR-214 plus nivolumab (anti-PD-1) in sarcoma; PD-1 is the therapeutic target of nivolumab.',[T('PD-1','measurement','Nivolumab is an anti-PD-1 antibody; PD-1 pathway is the therapeutic target')]))
res.append(r('NCT03282396',True,'Phase 2 trial of ibrutinib in untreated high risk smoldering mantle cell lymphoma; CD20 and cyclin D1 positivity are required for diagnosis and enrollment, constituting bioanalytical biomarker measurements.',[T('CD20','inclusion','CD20 positivity is required for MCL diagnosis and mandatory for enrollment')]))
res.append(r('NCT03282656',True,'Phase 1 pilot study of hematopoietic stem cell gene transfer for sickle cell disease; transgene vector copy number in peripheral blood and HbF levels are secondary outcome bioanalytical biomarkers.',[T('HbF','measurement','HbF induction is the therapeutic goal of BCL11a knockdown; HbF levels are secondary outcome endpoints for assessing gene therapy efficacy')]))
res.append(r('NCT03283137',True,'Phase 1 study of TGR-1202 (PI3K-delta inhibitor) plus pembrolizumab (anti-PD-1) in relapsed/refractory CLL and B-cell NHL; PD-1 is the therapeutic target of pembrolizumab.',[T('PD-1','measurement','Pembrolizumab is an anti-PD-1 antibody combined with TGR-1202 PI3K-delta inhibitor')]))
res.append(r('NCT03283384',True,'Phase 2 neoadjuvant study of ribociclib (CDK4/6 inhibitor) plus letrozole versus chemotherapy in luminal breast cancer; Ki67 complete cell cycle arrest is the primary endpoint and ER pathway activity is measured as secondary bioanalytical endpoints.',[T('CDK4/6','measurement','Ribociclib is a CDK4/6 inhibitor; CDK4/6 inhibition is the pharmacological basis of the investigational agent')],[N('Ki67','measurement','Complete cell cycle arrest defined as Ki67 IHC < 1% is the primary endpoint; Ki67 measured by IHC and mRNA is the central bioanalytical measure')]))
res.append(r('NCT03283605',True,'Phase 1/2 study of durvalumab (anti-PD-L1) plus tremelimumab (anti-CTLA-4) with SBRT for metastatic head and neck carcinoma; PD-L1 and CTLA-4 are both therapeutic targets of the investigational combination.',[T('PD-L1','measurement','Durvalumab is an anti-PD-L1 antibody (MEDI4736); PD-L1 pathway is the therapeutic target'),T('CTLA-4','measurement','Tremelimumab is an anti-CTLA-4 antibody; CTLA-4 pathway is the therapeutic target')]))
res.append(r('NCT03283878',False,'Phase 4 trial of perioperative antibiotic prophylaxis in total knee arthroplasty; primary endpoint is PJI rate by chart review with no bioanalytical biomarker measurements.'))
res.append(r('NCT03283917',True,'Phase 1 study of daratumumab (anti-CD38) plus ixazomib and dexamethasone in AL amyloidosis; CD38 is the molecular target of daratumumab.',[T('CD38','measurement','Daratumumab is an anti-CD38 monoclonal antibody; CD38 expression on plasma cells is the pharmacological target')]))
res.append(r('NCT03284385',True,'Phase 2 study of adavosertib (WEE1 inhibitor) in SETD2-deficient advanced solid tumors; SETD2 mutation status detected by CLIA-certified NGS is a required inclusion biomarker and represents bioanalytical genomic testing.',[],[N('SETD2','inclusion','Pathogenic loss of SETD2 detected by CLIA-certified NGS panel in tumor tissue is mandatory for enrollment')]))
res.append(r('NCT03284866',True,'Phase 3 trial of HPV vaccination in HIV-infected women; HIV RNA/viral load and HPV type/quantity are measured as bioanalytical biomarkers for inclusion and as predictors of sustained HPV absence.',[],[N('HPV type and quantity','inclusion','HIV RNA and HPV types/quantities are measured at baseline; HPV types are predictors of sustained absence as a secondary outcome'),N('HIV RNA','inclusion','HIV-1 infection documented by licensed rapid HIV test or HIV RNA viral load is mandatory for enrollment')]))
res.append(r('NCT03285412',True,'Phase 2 study of ribociclib (CDK4/6 inhibitor) with adjuvant endocrine therapy in ER-positive breast cancer; ctDNA clearance is the primary endpoint and CDK4/6 is the pharmacological target.',[T('CDK4/6','measurement','Ribociclib is a CDK4/6 inhibitor; CDK4/6 inhibition is the pharmacological basis of the investigational agent'),T('ctDNA','measurement','ctDNA clearance after 12 cycles of adjuvant ribociclib is the primary endpoint')]))
res.append(r('NCT03286530',False,'Phase 2 study of ruxolitinib (JAK inhibitor) maintenance after allogeneic stem cell transplantation for AML/MDS; primary endpoint is 1-year GVHD/relapse-free survival with no specific bioanalytical biomarker measurements described beyond standard clinical assessment.'))
res.append(r('NCT03286634',True,'Phase 2 study of chemotherapy protocol for Down syndrome ALL with risk classification guided by flow cytometry MRD; MRD level is the central bioanalytical biomarker guiding risk stratification.',[T('MRD','measurement','Risk classification is guided by flow MRD levels; MRD monitoring drives protocol risk stratification')]))
res.append(r('NCT03287271',False,'Phase 1/2 study of VS-6063 (FAK inhibitor) plus paclitaxel and carboplatin in platinum-resistant ovarian cancer; primary endpoints are safety and ORR with no specific bioanalytical biomarker measurements described.'))
res.append(r('NCT03288532',True,'Phase 3 adjuvant trial of durvalumab (anti-PD-L1) plus tremelimumab (anti-CTLA-4) in resected high-risk renal cell carcinoma; PD-L1 and CTLA-4 are both therapeutic targets of the investigational combination.',[T('PD-L1','measurement','Durvalumab is an anti-PD-L1 antibody; PD-L1 is the therapeutic target of the investigational agent'),T('CTLA-4','measurement','Tremelimumab is an anti-CTLA-4 antibody; CTLA-4 is the therapeutic target of the investigational agent')]))
out='//wsl.localhost/Ubuntu/home/jeanmfc/projects/ALEXIS/storage/snapshots/clinical_trials_v2/active_universe/llm_eval_results/task1/batch_02260.json'
os.makedirs(os.path.dirname(out),exist_ok=True)
json.dump(res,open(out,'w'),indent=2)
print('Written',len(res),'trials')
