import json,os
r=lambda nct,rel,rsn,tgts=None,novel=None:{"nct_id":nct,"relevant":rel,"reasoning":rsn,"targets":tgts or [],"novel_targets":novel or []}
T=lambda t,role,ev:{"target":t,"role":role,"result_use":"bioanalytical","safety_lab":False,"evidence":ev}
N=lambda n,role,ev:{"name":n,"role":role,"result_use":"bioanalytical","evidence":ev}
res=[]
res.append(r('NCT03269526',True,'Phase Ib/II study of anti-CD3 x anti-EGFR bispecific antibody armed T cells (EGFR BATs) for advanced pancreatic cancer; EGFR targeting is the mechanism and cellular/humoral anti-tumor responses measured in peripheral blood are bioanalytical endpoints.',[T('EGFR','measurement','Anti-CD3 x anti-EGFR bispecific antibody arms T cells to target EGFR-expressing pancreatic cancer cells')],[N('EGFR BATs cellular response','measurement','Cellular and humoral anti-pancreatic cancer responses measured in peripheral blood mononuclear cells as secondary outcomes')]))
res.append(r('NCT03269669',False,'Phase 2 trial in relapsed/refractory follicular lymphoma evaluating obinutuzumab combinations; primary endpoint is complete response by PET/CT imaging with no bioanalytical biomarker measurements in biological samples described.'))
res.append(r('NCT03270059',False,'Phase 2 feasibility study of ferumoxytol MRI for CNS abnormality imaging; outcomes are imaging-based visualization scores with no bioanalytical biomarker measurements in biological samples.'))
res.append(r('NCT03271372',True,'Phase 3 trial of adjuvant avelumab (anti-PD-L1) in Merkel cell carcinoma with lymph node metastases; PD-L1 is the therapeutic target and peripheral blood correlative studies are included as part of the study interventions.',[T('PD-L1','measurement','Avelumab is an anti-PD-L1 antibody; PD-L1 pathway is the therapeutic target of the investigational agent')]))
res.append(r('NCT03272334',True,'Phase I/II study of anti-CD3 x anti-HER2 bispecific antibody armed T cells (HER2 BATs) plus pembrolizumab in metastatic breast cancer; HER2 and PD-1 are both molecular targets requiring bioanalytical characterization.',[T('HER2','measurement','HER2 BATs (anti-CD3 x anti-HER2 bispecific antibody armed T cells) target HER2-expressing breast cancer cells'),T('PD-1','measurement','Pembrolizumab is an anti-PD-1 antibody used in combination with HER2 BATs')]))
res.append(r('NCT03272698',False,'Phase 4 randomized trial of ketamine-based therapy for treatment-resistant depression; primary endpoint is number of treatments to achieve MADRS remission with no bioanalytical biomarker measurements.'))
res.append(r('NCT03273413',True,'Phase 4 trial of pravastatin in early stage ADPKD; secondary outcomes include plasma levels of inflammatory cytokines and growth factors measured as bioanalytical biomarkers.',[],[N('Inflammatory cytokines','measurement','Plasma levels of inflammatory cytokines and growth factors are named secondary outcomes for assessing treatment effect on inflammation')]))
res.append(r('NCT03274375',True,'Phase 2 study of immunoadsorption therapy in pediatric anti-NMDAR encephalitis; anti-NMDAR antibodies in CSF are the diagnostic bioanalytical biomarker required for enrollment and the study is fundamentally based on measuring antibody levels.',[],[N('Anti-NMDAR antibodies','inclusion','Positive anti-NMDAR antibodies in CSF is mandatory for enrollment; antibody levels in CSF/serum define the disease and treatment response')]))
res.append(r('NCT03274479',False,'Phase 1 dose escalation study of PBF-1129 adenosine A2b receptor antagonist in NSCLC; primary endpoint is MTD determination; EGFR/ALK/ROS1 mutations are mentioned only as exclusion criteria for prior targeted therapy history, not as bioanalytical measurements.'))
res.append(r('NCT03274492',True,'Phase 3 study comparing polatuzumab vedotin plus R-CHP versus R-CHOP in previously untreated DLBCL; CD20-positive status is mandatory for enrollment and polatuzumab vedotin targets CD79b, representing bioanalytical biomarker measurements.',[T('CD20','inclusion','CD20-positive DLBCL is a mandatory inclusion criterion for enrollment; rituximab targets CD20')],[N('CD79b','measurement','Polatuzumab vedotin (anti-CD79b ADC) targets CD79b on B cells; CD79b expression is the pharmacological basis of the investigational agent')]))
res.append(r('NCT03275103',True,'Phase 1 study of cevostamab (anti-FcRH5 x anti-CD3 bispecific) in relapsed/refractory multiple myeloma; BCMA-like targets are assessed and PK/PD of the bispecific antibody in serum are secondary outcomes representing bioanalytical measurements.',[],[N('FcRH5 (FCRL5)','measurement','Cevostamab targets FcRH5 (FCRL5) on myeloma cells; serum PK of cevostamab is a secondary outcome')]))
res.append(r('NCT03275493',True,'Phase 1/2 study of CD19 CAR-T cells with CRS suppression technology in relapsed/refractory CD19+ ALL; CD19 positivity is required for enrollment and MRD negativity is a key efficacy endpoint.',[T('CD19','inclusion','Relapsed or refractory CD19+ ALL is the mandatory inclusion criterion; CAR-T cells are engineered to target CD19'),T('MRD','measurement','MRD negativity is a component of the complete remission secondary endpoint')]))
res.append(r('NCT03275584',False,'Phase 4 safety study of N-13 ammonia injection for PET myocardial perfusion imaging; outcomes are safety/adverse reaction assessments of the radiotracer with no bioanalytical biomarker measurements.'))
res.append(r('NCT03275974',True,'Phase 1 glutamine PET imaging study in metastatic RAS wild type colorectal cancer; RAS wild type status is a required inclusion criterion and gene expression analysis of archived tumor tissue is a secondary bioanalytical endpoint.',[],[N('RAS','inclusion','RAS wild type status is a mandatory inclusion criterion; eligible for anti-EGFR mAb therapy'),N('Gene expression','measurement','RNA-Seq gene expression analysis of archived primary and metastatic tissues is a secondary outcome')]))
res.append(r('NCT03277430',True,'Phase 3 uterus transplantation study; de novo donor-specific antibodies (DSA) monitoring is expected in the context of transplant immunosuppression management with tacrolimus, representing bioanalytical biomarker measurement.',[T('DSA','measurement','Transplant rejection monitoring requires DSA/anti-HLA antibody measurements; tacrolimus immunosuppression is the investigational approach')]))
res.append(r('NCT03277638',True,'Phase 1/2 study of laser interstitial thermotherapy (LITT) combined with pembrolizumab (anti-PD-1) for recurrent glioblastoma; PD-1 is the therapeutic target of pembrolizumab.',[T('PD-1','measurement','Pembrolizumab is an anti-PD-1 antibody; PD-1 pathway is the therapeutic target of the investigational combination')]))
res.append(r('NCT03277729',True,'Phase 1/2 study of CD20 CAR-T cells for relapsed/refractory B-cell non-Hodgkin lymphoma; CD20 positivity is required for enrollment and laboratory biomarker analysis is listed as a study intervention.',[T('CD20','inclusion','CD20-specific CAR-T cells target CD20-expressing B-cell lymphoma; CD20 positivity is required for enrollment')]))
res.append(r('NCT03278509',False,'Phase 4 registry-based randomized trial of long-term beta-blocker therapy post-myocardial infarction; primary endpoint is composite of death or MI with no bioanalytical biomarker measurements described.'))
res.append(r('NCT03278691',False,'Phase 4 trial of ketorolac for post-operative analgesia in spinal fusions; primary endpoint is fusion construct by X-ray with secondary outcomes of pain scores and morphine equivalents; no bioanalytical biomarker measurements.'))
res.append(r('NCT03278782',True,'Phase 1/2 study of pembrolizumab (anti-PD-1) plus romidepsin in relapsed/refractory peripheral T-cell lymphoma; PD-1 is the therapeutic target of pembrolizumab.',[T('PD-1','measurement','Pembrolizumab is an anti-PD-1 antibody; PD-1 pathway is the therapeutic target of the investigational combination')]))
out='//wsl.localhost/Ubuntu/home/jeanmfc/projects/ALEXIS/storage/snapshots/clinical_trials_v2/active_universe/llm_eval_results/task1/batch_02240.json'
os.makedirs(os.path.dirname(out),exist_ok=True)
json.dump(res,open(out,'w'),indent=2)
print('Written',len(res),'trials')
