import json,os
r=lambda nct,rel,rsn,tgts=None,novel=None:{"nct_id":nct,"relevant":rel,"reasoning":rsn,"targets":tgts or [],"novel_targets":novel or []}
T=lambda t,role,ev:{"target":t,"role":role,"result_use":"bioanalytical","safety_lab":False,"evidence":ev}
N=lambda n,role,ev:{"name":n,"role":role,"result_use":"bioanalytical","evidence":ev}
res=[]
res.append(r('NCT03258320',False,'Neoadjuvant chemotherapy study for prostate cancer with primary outcomes of disease-free and overall survival; no bioanalytical biomarker measurements described.'))
res.append(r('NCT03258567',True,'Phase 2 study of nivolumab (anti-PD-1) in EBV-positive lymphoproliferative disorders; PD-1 blockade is the therapeutic mechanism and EBV viral load PCR is a bioanalytical treatment response endpoint.',[T('PD-1','measurement','Nivolumab is an anti-PD-1 antibody; PD-1 pathway engagement is the pharmacological basis')],[N('EBV','inclusion','Eligibility requires EBV-positive confirmed disease; EBV viral load monitoring is an efficacy endpoint')]))
res.append(r('NCT03258658',False,'Phase 1 safety study of autologous engineered urethral constructs for urethral stricture; outcomes are urinary flow rates and adverse events with no bioanalytical biomarker measurements.'))
res.append(r('NCT03259867',True,'Phase 2 study of TATE with anti-PD-1 nivolumab for advanced liver cancer; PD-1 is the molecular target of nivolumab, qualifying as bioanalytical biomarker relevance.',[T('PD-1','measurement','Nivolumab is a PD-1 immune checkpoint inhibitor and is the investigational agent')]))
res.append(r('NCT03260023',True,'Phase Ib/II trial of TG4001 plus avelumab (anti-PD-L1) in HPV-16 positive malignancies; PD-L1 is the therapeutic target and HPV-16 status is a required bioanalytical inclusion biomarker.',[T('PD-L1','measurement','Avelumab is an anti-PD-L1 antibody used as the combinatorial checkpoint inhibitor')],[N('HPV-16','inclusion','Eligibility requires histologically documented HPV-16 positive cancer')]))
res.append(r('NCT03260491',True,'Phase 1 study of HER3-DXd (anti-HER3 ADC) in NSCLC; EGFR mutation status is required for dose escalation enrollment and KRAS-G12C mutation defines Cohort 5, representing bioanalytical genomic biomarker testing for drug development.',[T('EGFR','inclusion','Dose escalation requires EGFR activating mutation (exon 19 deletion, L858R) as mandatory inclusion criterion'),T('KRAS','inclusion','Cohort 5 evaluates HER3-DXd in NSCLC with KRAS-G12C mutation after failure of targeted therapy')],[N('HER3','measurement','HER3-DXd targets HER3; total anti-HER3 antibody PK is a secondary outcome; HER3 expression assessed for patient selection')]))
res.append(r('NCT03261102',True,'Therapeutic drug monitoring study of adalimumab in Crohn disease; measures adalimumab drug concentration, anti-drug antibodies, CRP, and fecal calprotectin as bioanalytical biomarkers to guide dose optimization.',[T('CRP','measurement','CRP < 5 mg/L is part of the primary composite remission endpoint; used as bioanalytical efficacy biomarker')],[N('Adalimumab drug concentration','measurement','TDM of adalimumab serum concentration at weeks 8 and 12 is a named secondary outcome; anti-adalimumab antibodies also measured'),N('Fecal calprotectin','measurement','Fecal calprotectin < 250 ug/g is part of the primary remission endpoint; bioanalytical marker of intestinal inflammation')]))
res.append(r('NCT03263572',True,'Phase 2 study of blinatumomab plus ponatinib in Ph+ ALL; molecular complete remission (BCR-ABL negativity) is a primary endpoint and NGS-based MRD assessment is a key exploratory objective.',[T('MRD','measurement','Complete molecular response is a primary endpoint; NGS-based MRD is an exploratory objective')],[N('BCR-ABL','inclusion','Ph+ ALL defined by t(9;22) and BCR-ABL positivity is mandatory; ABL1 kinase domain mutations are exploratory biomarkers')]))
res.append(r('NCT03263650',True,'Phase 2 study of olaparib PARP inhibitor maintenance in aggressive variant prostate cancer; PSA response rate is a secondary endpoint and DDR pathway genomic alterations in serial biopsies are bioanalytical correlative endpoints.',[T('PARP','measurement','Olaparib is a PARP inhibitor; PARP pathway is the pharmacological target of the maintenance therapy'),T('PSA','measurement','PSA response rate is a named secondary endpoint for evaluating treatment response')],[N('DDR pathway genes','measurement','Genomic alterations in DNA damage repair pathway genes assessed in serial biopsies are a secondary bioanalytical endpoint')]))
res.append(r('NCT03264131',True,'Phase 2 study of brentuximab vedotin (anti-CD30 ADC) plus CHEP in adult T-cell leukemia/lymphoma; CD30 positivity is required for BV maintenance eligibility, constituting a bioanalytical biomarker measurement for patient stratification.',[T('CD30','inclusion','CD30-positive ATLL required for BV maintenance; brentuximab vedotin targets CD30 assessed by biopsy')]))
res.append(r('NCT03264352',False,'Phase 4 cardiovascular outcomes trial in type 2 diabetes with high-normal blood pressure; primary endpoint is composite MACE with no bioanalytical biomarker measurements for drug development.'))
res.append(r('NCT03264664',False,'Phase 1 dose escalation study of E7386 WNT pathway inhibitor in advanced neoplasms; primary endpoints are DLTs and RP2D determination with no specific bioanalytical biomarker measurements described.'))
res.append(r('NCT03265431',False,'Phase 2 imaging study using 18F-TPP PET/MR for VT ablation guidance; outcomes are entirely imaging-based with no bioanalytical biomarker measurements in biological samples.'))
res.append(r('NCT03265808',True,'Phase 1/2 study of allogeneic MSCs in alcohol use disorder with major depression; serum CRP, TNF-alpha, and IL-6 are named secondary outcomes representing bioanalytical inflammatory biomarker measurements.',[T('CRP','measurement','Change in serum high-sensitivity CRP is a named secondary outcome; CRP >= 3.0 mg/L is an inclusion criterion'),T('IL-6','measurement','Change in serum IL-6 concentration is explicitly listed as a secondary outcome biomarker'),T('TNF','measurement','Change in serum TNF-alpha is explicitly listed as a secondary outcome biomarker')]))
res.append(r('NCT03266393',True,'Phase 4 tacrolimus formulation study in adolescent renal transplant recipients; de novo donor-specific anti-HLA antibodies measured by Luminex are a primary endpoint representing bioanalytical rejection biomarker measurement.',[T('DSA','measurement','De novo donor-specific anti-HLA antibody (dnDSA) appearance is a primary endpoint assessed by Luminex Single Antigen Bead assay'),T('HLA','measurement','Anti-HLA antibody testing by Luminex is the bioanalytical method for detecting dnDSA; IgG3 and C1q positive DSA are secondary endpoints')]))
res.append(r('NCT03266627',True,'Phase 2 study of adenovirus-specific CTLs in pediatric transplant recipients; quantitative ADV PCR viral load monitoring is the primary bioanalytical biomarker for treatment response assessment.',[],[N('ADV DNA','measurement','Quantitative ADV RT-PCR DNA copies monitored as primary bioanalytical measure of treatment response')]))
res.append(r('NCT03266640',True,'Phase 2 study of CMV-specific CTLs in pediatric transplant recipients; CMV quantitative PCR viral load is the primary bioanalytical biomarker for treatment response and patient eligibility.',[],[N('CMV DNA','measurement','Quantitative CMV qRT-PCR DNA copies monitored as primary bioanalytical efficacy measure')]))
res.append(r('NCT03266653',True,'Phase 2 study of EBV-specific CTLs in pediatric transplant recipients; EBV quantitative PCR viral load monitoring is the primary bioanalytical biomarker for treatment response and patient eligibility.',[],[N('EBV DNA','measurement','Quantitative EBV RT-PCR DNA copies monitored as primary bioanalytical efficacy measure')]))
res.append(r('NCT03267433',True,'Phase 3 trial in mantle cell lymphoma comparing auto-HCT plus rituximab versus rituximab alone; MRD status by NGS-based testing is the central stratification factor and a key secondary endpoint.',[T('MRD','measurement','MRD-negative status is the primary inclusion criterion; MRD conversion rate post-HCT is a key secondary endpoint')]))
res.append(r('NCT03268603',False,'Phase 2 study of intrathecal autologous MSCs for ALS; primary outcomes are adverse events and secondary outcomes are functional scales with no bioanalytical biomarker measurements described.'))
out='//wsl.localhost/Ubuntu/home/jeanmfc/projects/ALEXIS/storage/snapshots/clinical_trials_v2/active_universe/llm_eval_results/task1/batch_02220.json'
os.makedirs(os.path.dirname(out),exist_ok=True)
json.dump(res,open(out,'w'),indent=2)
print('Written',len(res),'trials')
